import esbuild from "esbuild";
import process from "process";
import fs from "node:fs";
import path from "node:path";
import { builtinModules } from "node:module";
import postcss from "postcss";
import prefixer from "postcss-prefix-selector";

const prod = process.argv[2] === "production";
const ROOT_CLASS = ".leovale-sheet-root";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Source: https://github.com/leovale/obsidian-sheet-notes
*/
`;

// The vendors' own banners lack @license markers, so esbuild's minifier drops
// them; MIT requires the notices to survive in redistributed copies.
const footer = `
/*!
 * Bundled third-party software (see THIRD-PARTY-NOTICES.md):
 * - jspreadsheet-ce 5.0.4 (https://github.com/jspreadsheet/ce)
 *   MIT License, Copyright (c) 2024 Jspreadsheet Ltd
 * - jsuites (https://github.com/jsuites/jsuites)
 *   MIT License, Jspreadsheet Ltd / Paul Hodel
 * - Jspreadsheet Extensions: Formula Basic (https://jspreadsheet.com)
 *   "License: This is a free software MIT"
 * - xlsx-js-style 1.2.0 (https://github.com/gitbrent/xlsx-js-style)
 *   SheetJS Community Edition 0.18.5 plus cell styles, maintained by Brent Ely
 *   Apache License 2.0, Copyright (C) 2012-present SheetJS LLC
 */
`;

/**
 * Keep the legacy code pages out of the bundle.
 *
 * `xlsx-js-style/dist/xlsx.min.js` ends with
 * `typeof require && (cptable = require("./cpexcel.js"))`, a RUNTIME guard for
 * old single-byte encodings in `.xls`, `.dbf` and friends. esbuild cannot know
 * the branch is dead and pulls the 472 KB table in: measured, the same bundle is
 * 1 239 911 B with it and 427 056 B without. We only ever touch `.xlsx`, which
 * is UTF-8 XML inside a zip, so the tables have nothing to do.
 */
const stubCodepagePlugin = {
	name: "stub-cpexcel",
	setup(build) {
		build.onResolve({ filter: /cpexcel(\.js)?$/ }, () => ({
			path: "cpexcel-stub",
			namespace: "leovale-stub",
		}));
		build.onLoad({ filter: /.*/, namespace: "leovale-stub" }, () => ({
			contents: "module.exports = undefined;",
			loader: "js",
		}));
	},
};

/**
 * Obsidian only ever loads `styles.css`. esbuild emits `main.css` for imported
 * CSS and Obsidian silently ignores it, so after every build we:
 *   1. read main.css (the vendor stylesheets),
 *   2. scope every selector under `.leovale-sheet-root`, rewriting
 *      html/body/:root instead of prefixing them (otherwise `:root` variables
 *      and `body { margin: 0 }` leak into the whole app),
 *   3. append our own Obsidian-variable theme bridge,
 *   4. write styles.css and delete main.css.
 */
const cssScopePlugin = {
	name: "scope-css-to-styles",
	setup(build) {
		build.onEnd(async (result) => {
			if (result.errors.length > 0) return;

			const mainCssPath = path.resolve("main.css");
			const themePath = path.resolve("src/styles/theme.css");
			const outPath = path.resolve("styles.css");

			let vendorCss = "";
			if (fs.existsSync(mainCssPath)) vendorCss = fs.readFileSync(mainCssPath, "utf8");

			let scoped = "";
			if (vendorCss.trim().length > 0) {
				const processed = await postcss([
					prefixer({
						prefix: ROOT_CLASS,
						transform(prefix, selector, prefixedSelector) {
							if (/^(html|body|:root)\b/.test(selector)) {
								return selector.replace(/^(html|body|:root)/, prefix);
							}
							return prefixedSelector;
						},
					}),
				]).process(vendorCss, { from: undefined });
				scoped = processed.css;
			}

			const theme = fs.readFileSync(themePath, "utf8");
			const out = [
				"/* leovale-sheets: vendor CSS, scoped to " + ROOT_CLASS + " */",
				scoped,
				"",
				"/* leovale-sheets: Obsidian theme bridge */",
				theme,
			].join("\n");

			// LF, no BOM.
			fs.writeFileSync(outPath, out.replace(/\r\n/g, "\n"), "utf8");
			if (fs.existsSync(mainCssPath)) fs.rmSync(mainCssPath);

			const mainJs = path.resolve("main.js");
			const jsSize = fs.existsSync(mainJs) ? fs.statSync(mainJs).size : 0;
			console.log(
				`[css] vendor ${vendorCss.length} B -> scoped ${scoped.length} B; ` +
					`styles.css ${fs.statSync(outPath).size} B; main.js ${jsSize} B`,
			);
		});
	},
};

const context = await esbuild.context({
	banner: { js: banner },
	footer: { js: footer },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2021",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	// MIT requires vendors' copyright notices to survive minification.
	legalComments: "eof",
	// Vendor CSS references SVG/PNG assets; inline them, no runtime fetches.
	loader: { ".svg": "dataurl", ".png": "dataurl", ".gif": "dataurl" },
	plugins: [cssScopePlugin, stubCodepagePlugin],
});

if (prod) {
	await context.rebuild();
	await context.dispose();
	process.exit(0);
} else {
	await context.watch();
}
